version: '3.4'

services:
  backend:
    image: registry.gitlab.com/antiretake/anti-retake/back-end/backend:latest
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
